# Generated by Django 4.2.8 on 2023-12-23 13:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://dummyimage.com/450x300/dee2e6/6c757d.jpg', max_length=255, verbose_name='image'),
        ),
    ]
